/**
 * MCP Error Codes
 *
 * Defines standardized error codes for MCP (Model Context Protocol) operations.
 * These codes categorize different failure types for connection, capability,
 * tool, and protocol errors.
 */

/**
 * MCP-specific error codes for categorizing different failure types
 */
export const MCP_ERROR_CODES = {
  // Connection lifecycle errors
  CONNECTION_FAILED: "MCP_CONNECTION_FAILED",
  CONNECTION_TIMEOUT: "MCP_CONNECTION_TIMEOUT",
  CONNECTION_LOST: "MCP_CONNECTION_LOST",
  CONNECTION_REFUSED: "MCP_CONNECTION_REFUSED",
  RECONNECTION_FAILED: "MCP_RECONNECTION_FAILED",

  // Capability negotiation errors
  CAPABILITY_NEGOTIATION_FAILED: "MCP_CAPABILITY_NEGOTIATION_FAILED",
  UNSUPPORTED_CAPABILITIES: "MCP_UNSUPPORTED_CAPABILITIES",
  INVALID_CAPABILITIES: "MCP_INVALID_CAPABILITIES",
  PROMPTS_NOT_SUPPORTED: "MCP_PROMPTS_NOT_SUPPORTED",
  RESOURCES_NOT_SUPPORTED: "MCP_RESOURCES_NOT_SUPPORTED",

  // Tool operation errors
  TOOL_DISCOVERY_FAILED: "MCP_TOOL_DISCOVERY_FAILED",
  TOOL_EXECUTION_FAILED: "MCP_TOOL_EXECUTION_FAILED",
  TOOL_NOT_FOUND: "MCP_TOOL_NOT_FOUND",
  TOOL_INVALID_PARAMS: "MCP_TOOL_INVALID_PARAMS",

  // Protocol errors
  PROTOCOL_ERROR: "MCP_PROTOCOL_ERROR",
  INVALID_RESPONSE: "MCP_INVALID_RESPONSE",
  JSONRPC_ERROR: "MCP_JSONRPC_ERROR",

  // General MCP errors
  UNKNOWN_ERROR: "MCP_UNKNOWN_ERROR",
} as const;
